import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    width: 150,
    height: 291,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "rgba(183, 29, 24, 1)",
    position: "relative",
    padding: 0,
  },
  title: {
    position: "absolute",
    top: 24,
    left: 72,
    fontWeight: "700",
    fontSize: 16,
    lineHeight: 16,
    textTransform: "uppercase",
    color: "#FFF5CC",
  },
  chip: {
    position: "absolute",
    top: 44,
    left: 56,
    height: 20,
    borderRadius: 999,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  chipText: {
    fontWeight: "700",
    fontSize: 8,
    lineHeight: 8,
    textTransform: "uppercase",
    color: "rgba(122, 9, 22, 1)",
  },
  product: {
    position: "absolute",
    top: 75,
    left: 0.23,
    width: 150.2238,
    height: 141.1686,
  },
  row: {
    position: "absolute",
    flexDirection: "row",
    alignItems: "center",
    gap: 3.73,
  },
  bullet: {
    width: 9.32,
    height: 9.32,
    marginRight: 4,
  },
  benefit: {
    fontWeight: "600",
    fontSize: 7.46,
    lineHeight: 7.46 * 1.5,
    letterSpacing: 0.02 * 16,
    color: "#FFFFFF",
  },
});
